### ISSUE TITLE
Crash on startup after updating from 0.61.0 to 0.62.0: Uint8Array.fromBase64 is not a function

### ISSUE THREAD

**Issue by AIRLord19** [Voxelum/x-minecraft-launcher#1562]
### 是否已经有人报告过这个问题？

- [x] 我已经搜索过现有的问题

### 启动器版本

0.61.0 - 0.62.0

### 操作系统

Windows

### 架构

x64

### 当前行为

The launcher crashes immediately upon startup after updating from version 0.61.0 to 0.62.0. A Windows error dialog appears saying: "A JavaScript error occurred in the main process. Uncaught Exception: TypeError: Uint8Array.fromBase64 is not a function".

<img width="780" height="488" alt="Image" src="https://github.com/user-attachments/assets/51fb7e1d-a154-409f-941d-6c9728a170c1" />

### 期望行为

The launcher should start normally without any JavaScript errors.

### 复现步骤

1. Have XMCL version 0.61.0 installed.
2. Update the launcher to version 0.62.0.
3. Launch the application.
4. Observe the JavaScript error crash dialog.

**Comment by ci010** [comment]
## Root cause confirmed

This is an **esbuild binary-loader compatibility regression**, not an MSAL/authentication failure.

`xmcl-runtime` imports two embedded Java `.class` files (`JavaProxy.class` and `MultiJarLauncher.class`). After the v0.62 upgrade to esbuild 0.28, the unrestricted build target emitted these top-level initializers in `app.asar/index.js`:

```js
var JavaProxy_default = Uint8Array.fromBase64("...")
var MultiJarLauncher_default = Uint8Array.fromBase64("...")
```

Electron 43's embedded Node runtime does not expose `Uint8Array.fromBase64`, so evaluating the main bundle crashes immediately, before the launcher window is created. This explains why a fresh development/e2e profile can miss the issue while production v0.62 crashes at startup.

## Fix

Local commit `758991dd0` sets the main-process esbuild target to `node18`. Esbuild now emits its compatibility helper instead:

```js
var __toBinaryNode = Uint8Array.fromBase64 || ((base64) => new Uint8Array(Buffer.from(base64, "base64")))
var JavaProxy_default = __toBinaryNode("...")
```

This works whether the runtime provides `Uint8Array.fromBase64` or not. The Electron main build and typecheck pass with the corrected emitted output.

**Comment by ci010** [comment]
@AIRLord19 你是不是下载的zip的启动器？你重新下一个zip版的就好了，应该是自动更新弄出问题了

**Comment by AIRLord19** [comment]
@ci010 Thanks, it helped.
